version: '3.1'

services:
  survey:
    build: .
    restart: always
    container_name: survey-service
    environment:
      - DB_HOST=db
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: survey-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=surveydb
      - MYSQL_USER=survey
      - MYSQL_PASSWORD=12345
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
